### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by shirshak55** [bit-country/Bit-Country-Blockchain#61]
I was reading to read the code. So I decided to try it in my own pc.
But alas I am unable to build it.

OS: Windows 10

This error message is:
```
quantum@quanta MINGW64 ~/Desktop/projects/Bit-Country-Blockchain (master)
$ cargo build --release
error: failed to read `C:\Users\quantum\Desktop\projects\Bit-Country-Blockchain\pallets\auction-manager
\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)

```

I thought it might be some pesky windows error but I think its due to 
missing auction-manager.

```
https://github.com/bit-country/Bit-Country-Blockchain/blob/723a4125c07b380fd908110abb7a784015c2df28/pallets/auction/Cargo.toml#L40
```

Has auction manager but I don't see that folder in that pallets folder. 
So I think its missing in this repo?

Update: Make text < 80 columns

**Comment by justinphamnz** [comment]
#62 You can check this PR.
